In [1]:
import numpy as np
from statistical import corr
# dimesion of BOLDcorr should be equal to iEEGcorr's

In [2]:
### pearson
BOLDcorrMat = np.random.rand(50,50)
iEEGcorrMat = BOLDcorrMat

[corrCoef, pvalue, BOLDvec, iEEGvec] = corr(iEEGcorrMat, BOLDcorrMat, "pearson")

print(corrCoef, pvalue)
print(BOLDvec)
print(iEEGvec)

1.0 0.0
[0.18533855 0.04375281 0.87918148 ... 0.55470798 0.90584367 0.60729994]
[0.18533855 0.04375281 0.87918148 ... 0.55470798 0.90584367 0.60729994]


In [3]:
### Spearman rank-order correlation coefficient
BOLDcorrMat = np.random.rand(50,50)
iEEGcorrMat = BOLDcorrMat

[corrCoef, pvalue, BOLDvec, iEEGvec] = corr(iEEGcorrMat, BOLDcorrMat, "spearman")

print(corrCoef, pvalue)
print(BOLDvec)
print(iEEGvec)

1.0 0.0
[0.09443457 0.56584903 0.52448743 ... 0.0570009  0.5658424  0.14206155]
[0.09443457 0.56584903 0.52448743 ... 0.0570009  0.5658424  0.14206155]
